field: fdbfc807-7ac7-4c48-bdf5-a87b54757f92 # Blocks Builder
fieldLayouts:
  1f91db56-2a74-4151-8443-4fe3ff937aac:
    tabs:
      -
        elements:
          -
            fieldUid: edf10d2e-0ce3-4149-9d10-f6fa278d1aa6 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05670d2d-f732-4c41-9fd8-1daaec6645bf
            warning: null
            width: 100
          -
            fieldUid: 290a0c6b-f5e6-45ef-bb53-5a0518dd6027 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c86797d2-c2d9-4b4c-88e4-a9ef2b59b0f8
            warning: null
            width: 100
        name: Content
        uid: 40ea4986-b95e-4a9a-bccc-c4cf0d52efcb
fields:
  290a0c6b-f5e6-45ef-bb53-5a0518dd6027: # Copy
    columnSuffix: wayfykkv
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: null
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  edf10d2e-0ce3-4149-9d10-f6fa278d1aa6: # Heading
    columnSuffix: bwfhnnas
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: richText
name: 'Rich Text'
sortOrder: 1
