fieldLayouts:
  dc56816c-7f67-4c4e-87ce-1fb7811e5800:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c763df25-1d8e-48f3-b7fc-39229798d08e
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 94b1b58e-c23d-421b-a198-3cf794dffd09
          -
            fieldUid: fdbfc807-7ac7-4c48-bdf5-a87b54757f92 # Blocks Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 266bceae-3193-4b92-bb54-b95c23230099
            warning: null
            width: 100
        name: Content
        uid: 17779d03-544d-4a7f-8717-5505c4130dfd
handle: default
hasTitleField: true
name: Default
section: be626170-6d2a-4baf-9f4e-b9b062fc0092 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
